openapi: 3.0.0

info:
    title: Path calculation results using TOS
    description: Path calculation results using TOS.
    version: 1.0.0

paths:
    /securetrack/api/rule_search.json?lasthitgreater:30%20rule.isdisabled:false%20action:allow:
        get:
            operationId: UnusedRules
            summary: Shows the count of unused rules per device.
            responses:
                200:
                    description: List of devices with an unused rule count per device.
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    device_list:
                                        type: object
                                        properties:
                                            device:
                                                type: array
                400:
                    description: Value is missing or not valid
    /securetrack/api/rule_search/{deviceId}.json?lasthitgreater:30%20rule.isdisabled:false%20action:allow:
        get:
            operationId: UnusedRulesPerDevice
            summary: Retrieve unused rules from a device based on the device id.
            parameters:
                -   in: path
                    name: deviceId
                    required: true
                    description: The device id to lookup for unused rules
                    schema:
                        type: integer
                -   $ref: '#/components/parameters/start'
                -   $ref: '#/components/parameters/count'
            responses:
                200:
                    description: Return object of unused rules
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    rules:
                                        type: object
                                        properties:
                                            count:
                                                type: integer
                                            total:
                                                type: integer
                                            rule:
                                                type: array
                404:
                    description: Value is missing or not valid
    /securetrack/api/rule_search.json?shadowed:true:
        get:
            operationId: ShadowedRules
            summary: Returns rules that are shadowed
            responses:
                200:
                    description: List of shadowed rules.
                400:
                    description: Value is missing or not valid
    /securetrack/api/rule_search/{deviceId}.json?shadowed:true:
        get:
            operationId: ShadowedRulesForDeviceId
            summary: Returns rules that are shadowed for a device id
            parameters:
                -   in: path
                    name: deviceId
                    required: true
                    description: The device id to lookup for shadowed rules
                    schema:
                        type: integer
            responses:
                200:
                    description: List of shadowed rules.
                400:
                    description: Value is missing or not valid
    /securetrack/api/rule_search.json?permissiveness.level:high:
        get:
            operationId: PermissivenessLevelHigh
            summary: Returns rules with the high permissiveness level indicating how much traffic is allowed by the rule.
            responses:
                200:
                    description: List of high permissiveness level rules.
                400:
                    description: Value is missing or not valid
    /securetrack/api/rule_search/{deviceId}.json?permissiveness.level:high:
        get:
            operationId: PermissivenessLevelHighForDeviceId
            summary: Returns rules for a device id that have high permissiveness level
            parameters:
                -   in: path
                    name: deviceId
                    required: true
                    description: The device id to lookup for high permissiveness level rules
                    schema:
                        type: integer
            responses:
                200:
                    description: List of high permissiveness level rules.
                400:
                    description: Value is missing or not valid
    /securetrack/api/rule_search.json?violations.isempty:false:
        get:
            operationId: Violations
            summary: Search for rules that have violations. It retrieves a list of rules where the violations field is not empty, indicating that these rules have been flagged for one or more issues.
            responses:
                200:
                    description: List of high permissiveness level rules.
                400:
                    description: Value is missing or not valid
    /securetrack/api/rule_search/{deviceId}.json?violations.isempty:false:
        get:
            operationId: PermissivenessLevelHighForDeviceId
            summary: Used to search for rules with violations on a specific device. By specifying the deviceId, it retrieves a list of rules associated with that device where the violations field is not empty
            parameters:
                -   in: path
                    name: deviceId
                    required: true
                    description: The device id to lookup for rules with violations
                    schema:
                        type: integer
            responses:
                200:
                    description: List of high permissiveness level rules.
                400:
                    description: Value is missing or not valid


components:
    parameters:
        searchText:
            in: query
            name: 'search_text'
            required: true
            schema:
                type: string
                default: 'lasthitgreater:30 rule.isdisabled:false action:allow'
            allowEmptyValue: false
            allowReserved: true
        start:
            in: query
            name: start
            required: true
            schema:
                type: integer
                default: 0
                minimum: 0
        count:
            in: query
            name: count
            required: true
            schema:
                type: integer
                default: 3
                minimum: 3
                maximum: 10