openapi: 3.0.0

info:
    title: Path calculation results using TOS
    description: Path calculation results using TOS.
    version: 1.0.0

paths:
    /securetrack/api/topology/path.json:
        get:
            operationId: topologyPath
            summary: Get path for specified traffic.
            description: |
                Retrieve information of network access status.
                #ExamplePrompts Find traffic from source IP 10.1.0.0/24 to destination 10.1.3.0/24 with service HTTP
                #ExamplePrompts Can 118.25.6.39 access 10.200.10.1 using any service? 
                #ExamplePrompts Check if traffic allow between 192.168.1.1 and 10.100.35.1?
            parameters:
                -   $ref: '#/components/parameters/src'
                -   $ref: '#/components/parameters/dst'
                -   $ref: '#/components/parameters/srv'
            responses:
                200:
                    description: Path calculation results
                400:
                    description: Value is missing or not valid
    /securetrack/api/devices/{deviceId}.json:
        get:
            operationId: UnusedRulesDeviceInformation
            summary: Get device details based on the device id the way it is stored in SecureTrack.
            description: |
                Retrieve information about device using the device id.
                #ExamplePrompts Can you provide some details about device id 1 using the Tufin Firewall Management plugin?
            parameters:
                -   in: path
                    name: deviceId
                    required: true
                    description: The device id to lookup for unused rules
                    schema:
                        type: string
            responses:
                200:
                    description: OK

components:
    parameters:
        src:
            in: query
            name: src
            required: true
            allowEmptyValue: false
            schema:
                type: string
                default: 'any'
        dst:
            in: query
            name: dst
            required: true
            allowEmptyValue: false
            schema:
                type: string
                default: 'any'
        srv:
            in: query
            name: service
            required: true
            allowEmptyValue: false
            schema:
                type: string
                default: 'any'