openapi: 3.0.0

info:
    title: Path calculation results using TOS
    description: Path calculation results using TOS.
    version: 1.0.0

paths:
    /securechangeworkflow/ipc/securechange/workflows/active_workflows.json:
        get:
            operationId: ActiveWorkflowList
            summary: Returns active workflow list defined in SecureChange.
            responses:
                200:
                    description: OK
                400:
                    description: <TYPE> is not a valid workflow type
    /securechangeworkflow/ipc/securechange/workflows/active_workflows.json?type=ACCESS_REQUEST:
        get:
            operationId: AccessRequestWorkflows
            summary: The Access-Request workflow can either allow or block traffic to a service from the source to the destination.
            responses:
                200:
                    description: OK
                400:
                    description: <TYPE> is not a valid workflow type
    /securechangeworkflow/ipc/securechange/workflows/active_workflows.json?type=RULE_DECOMMISSION:
        get:
            operationId: RuleDecommissionWorkflows
            summary: Rule decommission workflow list for mitigating security issues, such as disabling unused rules.
            responses:
                200:
                    description: OK
                400:
                    description: <TYPE> is not a valid workflow type
